version: '2'

services:
  website:
    build: .
    links:
      - db
    env_file:
      - '.env'
    ports:
      - '80:5000'
    volumes:
      - './app:/home/App/app'

  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: labton
        MYSQL_PASSWORD: labton
        MYSQL_DATABASE: labton
